// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ubicua_Lectura_de_Datos.Db;

#nullable disable

namespace Ubicua_Lectura_de_Datos.Migrations
{
    [DbContext(typeof(UbicuaDbContext))]
    [Migration("20240124210854_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ubicua_Lectura_de_Datos.Db.Dato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<float>("gx")
                        .HasColumnType("real");

                    b.Property<float>("gy")
                        .HasColumnType("real");

                    b.Property<float>("gz")
                        .HasColumnType("real");

                    b.Property<float>("hum")
                        .HasColumnType("real");

                    b.Property<float>("temp")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Datos");
                });
#pragma warning restore 612, 618
        }
    }
}
